import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:msloyalty/Models/VehicleModel.dart';
import 'package:msloyalty/Services/vehicle_service.dart';
import 'package:msloyalty/Services/notification_service.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class VehicleDetailScreen extends StatefulWidget {
  final VehicleModel? vehicle;
  const VehicleDetailScreen({super.key, this.vehicle});

  @override
  State<VehicleDetailScreen> createState() => _VehicleDetailScreenState();
}

class _VehicleDetailScreenState extends State<VehicleDetailScreen> {
  final _formKey = GlobalKey<FormState>();
  final _vehicleService = VehicleService();

  late TextEditingController _plateController;
  late TextEditingController _brandController;
  late TextEditingController _modelController;
  DateTime? _oilDate;
  DateTime? _insuranceDate;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _plateController = TextEditingController(
      text: widget.vehicle?.licensePlate,
    );
    _brandController = TextEditingController(text: widget.vehicle?.brand);
    _modelController = TextEditingController(text: widget.vehicle?.model);
    _oilDate = widget.vehicle?.lastOilChangeDate;
    _insuranceDate = widget.vehicle?.insuranceExpiryDate;
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSaving = true);
    try {
      final user = Supabase.instance.client.auth.currentUser;
      if (user == null) return;

      if (widget.vehicle == null) {
        // Add new
        final newVehicle = VehicleModel(
          id: '', // Will be generated by Supabase
          userId: user.id,
          licensePlate: _plateController.text,
          brand: _brandController.text,
          model: _modelController.text,
          lastOilChangeDate: _oilDate,
          insuranceExpiryDate: _insuranceDate,
          createdAt: DateTime.now(),
        );
        await _vehicleService.addVehicle(newVehicle);
      } else {
        // Update existing
        await _vehicleService.updateVehicle(widget.vehicle!.id, {
          'license_plate': _plateController.text,
          'brand': _brandController.text,
          'model': _modelController.text,
          'last_oil_change_date': _oilDate?.toIso8601String().split('T')[0],
          'insurance_expiry_date': _insuranceDate?.toIso8601String().split(
            'T',
          )[0],
          'updated_at': DateTime.now().toIso8601String(),
        });
      }

      _scheduleReminders(_plateController.text);

      if (mounted) Navigator.pop(context, true);
    } catch (e) {
      setState(() => _isSaving = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  void _scheduleReminders(String vehiclePlate) {
    NotificationService.scheduleVehicleReminders(
      licensePlate: vehiclePlate,
      lastOilChangeDate: _oilDate,
      insuranceExpiryDate: _insuranceDate,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.vehicle == null ? 'Add Vehicle' : 'Edit Vehicle',
          style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildTextField(
                'License Plate (e.g. 1A/1234)',
                _plateController,
                true,
              ),
              const SizedBox(height: 20),
              _buildTextField('Brand (e.g. Toyota)', _brandController, false),
              const SizedBox(height: 20),
              _buildTextField('Model (e.g. Alphard)', _modelController, false),
              const SizedBox(height: 30),
              const Text(
                'Reminders',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
              ),
              const SizedBox(height: 16),
              _buildDatePicker(
                'Last Oil Change Date',
                _oilDate,
                (date) => setState(() => _oilDate = date),
              ),
              const SizedBox(height: 16),
              _buildDatePicker(
                'Insurance Expiry Date',
                _insuranceDate,
                (date) => setState(() => _insuranceDate = date),
              ),
              const SizedBox(height: 40),
              SizedBox(
                width: double.infinity,
                height: 52,
                child: ElevatedButton(
                  onPressed: _isSaving ? null : _save,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF1B4F72),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: _isSaving
                      ? const CircularProgressIndicator(color: Colors.white)
                      : Text(
                          widget.vehicle == null
                              ? 'ADD VEHICLE'
                              : 'UPDATE VEHICLE',
                          style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(
    String label,
    TextEditingController controller,
    bool required,
  ) {
    return TextFormField(
      controller: controller,
      decoration: InputDecoration(
        labelText: label,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        filled: true,
        fillColor: Colors.grey.withOpacity(0.05),
      ),
      validator: required ? (v) => v!.isEmpty ? 'Required' : null : null,
    );
  }

  Widget _buildDatePicker(
    String label,
    DateTime? date,
    Function(DateTime) onSelect,
  ) {
    return InkWell(
      onTap: () async {
        final selected = await showDatePicker(
          context: context,
          initialDate: date ?? DateTime.now(),
          firstDate: DateTime(2000),
          lastDate: DateTime(2100),
        );
        if (selected != null) onSelect(selected);
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: BoxDecoration(
          border: Border.all(color: Colors.grey.shade400),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    label,
                    style: const TextStyle(fontSize: 12, color: Colors.grey),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    date != null
                        ? DateFormat('dd MMM yyyy').format(date)
                        : 'Select Date',
                    style: const TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
            const Icon(
              Icons.calendar_today,
              size: 20,
              color: Color(0xFF1B4F72),
            ),
          ],
        ),
      ),
    );
  }
}
